### ISSUE TITLE
Support `!:` commit syntax for breaking changes

### ISSUE THREAD

**Issue by mikeal** [mikeal/merge-release#26]
The current rules only support the old “BREAKING” message. Conventional commits added a “fix!:” and “feat!:” for signaling breaking changes. We should just parse for “!:” for a major version bump.

**Comment by honzabilek4** [comment]
Hello @mikeal, 
not everyone uses conventional commits. Can we make these keywords configurable, so everyone can adjust it to their liking?
I would like to submit a PR for that.

**Comment by mikeal** [comment]
i’d like the interface to be stable and consistent. it’s not that i’m adamant that people use conventional commits, i just don’t think this will be a very maintainable project if we start allowing that level of customization. i feel the same way about configuring whether or not every commit releases or just some, the consistency is part of the interface and keeps the usage simple.

there’s plenty of other projects for doing releases though, many of which are highly configurable like https://github.com/googleapis/release-please

**Comment by honzabilek4** [comment]
Okay, 
I'll use some other action instead.

**Comment by Sergio6690** [comment]
1. > ### _**zz**_
