### ISSUE TITLE
Error: spawn git ENOENT

### ISSUE THREAD

**Issue by tlvince** [mikeal/merge-release#3]
Thanks for this action. I've integrated into a project (see [npm-publish.yml](https://github.com/tlvince/web-audio-wave-recorder/blob/a63197ba94d21e1acb2493135f99576bbc06a130/.github/workflows/npm-publish.yml)); the build is green, but the [merge-release step failed](https://github.com/tlvince/web-audio-wave-recorder/runs/210090326#step:7:7) with `Error: spawn git ENOENT`. That error reads like `git` isn't installed in the container. However, the workflow's using `ubuntu-latest` and the action's using `node:10-slim`, both of which have `git` install AFAIK. Any ideas?

**Comment by tlvince** [comment]
Switched to `mikeal/merge-release@master` and the [build passed](https://github.com/tlvince/web-audio-wave-recorder/runs/210097076#step:7:5). Closing (it'd be nice if you could tag the latest) :+1:

**Comment by mikeal** [comment]
which version were you using before?

this auto-publishes to npm but marketplace releases are still manual :(

**Comment by tlvince** [comment]
I was using v1.9.2. Will switch over to 2.2.6. Thanks!
